### ISSUE TITLE
how to train on S3DIS using xyz+rgb

### ISSUE THREAD

**Issue by TangYuan96** [RunpeiDong/ACT#3]
Firstly, thanks for your sharing so outstanding work!!

I want to try to train ACT  on S3DIS using xyz+rgb， 
but paper and coder seem to train only using xyz,

could you help   to tell me how to do this? 

Thanks a lot!

**Comment by RunpeiDong** [comment]
Hi @TangYuan96,

Thanks for your interest!

- You need to modify the data loader by changing the input `current_points` with full 6-dim xyz+rgb as inputs but not current `current_points[:, :3]`.
- Besides, the input to the model should also be modified to be able to take 6-dim inputs. So we have to pretrain the model on xyz+rgb input data (which is not conducted because ShapeNet does not have that). Also, please note that the grouping operation should take this into consideration.
- Btw, I have implemented training with RGB inputs before. 😸I'm very happy to send you the codes through email when I have time, and if you need help (please send me a request email).

**Comment by TangYuan96** [comment]
Thanks a lot !!!

I have sent the email to you
